config/routes.rb
Tydes::Application.routes.draw do
  resources :detections do
    member do
      get :test, :save, :results, :comment, :commentsave
    end

    collection do
      get :search, :as => :search
      get :download, :as => :download
      get :imagedownload, :as => :imagedownload
      get :comments, :as => :comments
    end
  end

  root to: 'detections#new'

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/news',  to: 'static_pages#updates'

end

app/models/detection.rb
# == Schema Information
#
# Table name: detections
#
#  id                   :integer          not null, primary key
#  user                 :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  code                 :string(255)
#  positive_trainingset :text
#  value                :text(255)
#  positive_training    :text
#  fn                   :integer
#  fp                   :integer
#  tn                   :integer
#  tp                   :integer
#  negative_training    :text
#  sight                :integer
#  currId               :integer
#  nickname             :string(255)
#  comment              :text
#

class Detection < ActiveRecord::Base
	serialize :value, Hash
	serialize :positive_training, Hash
	serialize :negative_training, Hash

	attr_accessible :user, :value, :code, :trainingset, :fp, :fn, :tp, :tn, :sight, :currId, :nickname

	validates :user, :numericality => { :only_integer => true }
	validates :sight, :numericality => { :only_integer => true }
end

app/controllers/detections_controller.rb
require 'will_paginate/array'
require 'action_view/helpers/number_helper'
require 'csv'

class DetectionsController < ApplicationController

	include ActionView::Helpers::NumberHelper

	def new
		@detection = Detection.new
	end

	def show
		@detection = Detection.find(params[:id])

		@positive_keys = @detection.positive_training.keys
		@negative_keys = @detection.negative_training.keys
		
	end

	def create
		@detection = Detection.new(params[:detection])

		begin
			tmp = (0..4).map{65.+(rand(26)).chr}.join
			[1,3].each do |k|
				tmp[k] = (1+rand(9)).to_s
			end
		end while (Detection.find_by_code(tmp))

		@detection.code = tmp

    	if @detection.save
    		# flash[:success] = "Welcome to the training phase!"

    		#shuffle positive and select same number of negatives for training
    		pos_ids = (1..Positive.count).to_a.shuffle
    		neg_ids = (1..Negative.count).to_a.shuffle[0..Positive.count-1]

    		# build positive training set
    		@detection.positive_training = Hash.new

    		pos_ids.each do |pid|
    			pim = Positive.find(pid)
    			@detection.positive_training[pim.code] = [pid, (pim.dir + pim.name)]
    			#pim.trainings += 1
    			#pim.save
    		end

    		#build negative training set
    		@detection.negative_training = Hash.new

    		neg_ids.each do |nid|
    			nim = Negative.find(nid)
    			@detection.negative_training[nim.code] = [nid, (nim.dir + nim.name)]
    			#nim.trainings += 1
    			#nim.save
    		end

    		#build test set
    		tmpkeys = Array.new

    		#shuffle positive and select same number of negatives for detection
    		eval_pos_ids = (1..Evalpositive.count).to_a.shuffle
    		eval_neg_ids = (1..Evalnegative.count).to_a.shuffle[0..Evalpositive.count-1]

    		(0..Evalpositive.count-1).each do |k|
    			pim = Evalpositive.find(eval_pos_ids[k])
    			nim = Evalnegative.find(eval_neg_ids[k])
    			tmpkeys << [pim.code, '1', (pim.dir + pim.name), eval_pos_ids[k]]
    			tmpkeys << [nim.code, '0', (nim.dir + nim.name), eval_neg_ids[k]]
    			#pim.detections += 1
    			#nim.detections += 1
    		end

    		tmpkeys.shuffle!

    		(0..tmpkeys.length-1).each do |j|
    			# key is CODE, value is an array made with id, type, name, detection, time
    			@detection.value[tmpkeys[j][0]] = [tmpkeys[j][3], tmpkeys[j][1], tmpkeys[j][2], 'u', 0]
    		end

			@detection.tp = 0
			@detection.tn = 0
			@detection.fp = 0
			@detection.fn = 0

			@detection.currId = 0

    		@detection.save

      		redirect_to @detection
    	else
			render 'new'
		end
	end

	def test
		@detection = Detection.find(params[:id])

		@positive_keys = @detection.positive_training.keys
		@negative_keys = @detection.negative_training.keys
		
		# NB: NOW IS ACCURACY
		f1den = @detection.tp + @detection.fn + @detection.fp + @detection.tn

		if f1den == 0
			@f1score = number_with_precision(0.0);
		else
			@f1score = number_with_precision( ( @detection.tp.to_f + @detection.tn.to_f ) / f1den.to_f * 100 )
		end

		sensden = @detection.tp + @detection.fn

		if sensden == 0
			@sensitivity = number_with_precision(0.0)
		else
			@sensitivity = number_with_precision( @detection.tp.to_f / sensden.to_f * 100 )
		end

		specden = @detection.tn + @detection.fp
		
		if specden == 0
			@specificity = number_with_precision(0.0)
		else
			@specificity = number_with_precision( @detection.tn.to_f / specden.to_f * 100 )
		end

		#@image_keys = @detection.value.keys.paginate(:page => params[:page], :per_page => 5)
		@curr_image_code = @detection.value.keys[@detection.currId]

		#save at beginning of test, to use "updated_at" as a time reference
		if @detection.currId == 0
			@detection.save
		end
	end

	def save
		act_t = Time.now
		@detection = Detection.find(params[:id])

		selected = false

		guess = 0

		curr_image_code = @detection.value.keys[@detection.currId]

		params.keys.each do |k|
			if !k["mit"].nil?
				# look for codeputs "PARAMS2 #{params}"
				puts "found submit"
				pim = Evalpositive.find_by_code(curr_image_code)
				
				if pim != nil
					# it is a positive image
					if !k['pp'].nil?
						selected = true
						guess = 1
						#it is detected as positive
						pim.positives += 1
						#update detection
						@detection.value[curr_image_code][3] = 1.0
						@detection.tp += 1
					elsif !k['qp'].nil?
						selected = true
						guess = 2
						#it is detected as positive
						pim.positives += 1
						#update detection
						@detection.value[curr_image_code][3] = 0.75
						@detection.tp += 1
					elsif !k['qn'].nil?
						selected = true
						guess = 3
						#update detection
						@detection.value[curr_image_code][3] = 0.25
						@detection.fn += 1
					elsif !k['nn'].nil?
						selected = true
						guess = 4
						#update detection
						@detection.value[curr_image_code][3] = 0.0
						@detection.fn += 1					
					end
					pim.save
					@detection.value[curr_image_code][4] = (act_t - @detection.updated_at).to_i
				else
					nim = Evalnegative.find_by_code(curr_image_code)

					if nim != nil
						# it is a negative image
						nim.detections += 1
						if !k['pp'].nil?
							selected = true
							guess = 5
							#it is detected as positive
							nim.positives += 1
							#update detection
							@detection.value[curr_image_code][3] = 1.0
							@detection.fp += 1
						elsif !k['qp'].nil?
							selected = true
							guess = 6
							#it is detected as positive
							nim.positives += 1
							#update detection
							@detection.value[curr_image_code][3] = 0.75
							@detection.fp += 1
						elsif !k['qn'].nil?
							selected = true
							guess = 7
							#update detection
							@detection.value[curr_image_code][3] = 0.25
							@detection.tn += 1
						elsif !k['nn'].nil?
							selected = true
							guess = 8
							#update detection
							@detection.value[curr_image_code][3] = 0.0
							@detection.tn += 1					
						end
						nim.save
						@detection.value[curr_image_code][4] = (act_t - @detection.updated_at).to_i
					end
				end
			end
		end

		#params[:pos_page] = params['cpp']
		#params[:neg_page] = params['cnp']

		if !selected
			flash[:warning] = "Please classify Image or press Finish"
			#redirect_to test_detection_path(@detection, :anchor => "samples")
			redirect_to test_detection_path(@detection)
		else
			case guess
				when 1
					flash[:success] = "Correct! last image was a Mitosis"
				when 2
					flash[:success] = "Your guess was right: last image was a Mitosis"
				when 3
					flash[:error] = "Your guess was wrong: last image was a Mitosis"
				when 4
					flash[:error] = "Sorry! last image was a Mitosis"
				when 5
					flash[:error] = "Sorry! last image was a NON Mitosis"
				when 6
					flash[:error] = "Your guess was wrong: last image was a NON Mitosis"
				when 7
					flash[:success] = "Your guess was right: last image was a NON Mitosis"
				when 8
					flash[:success] = "Correct! last image was a NON Mitosis"
			end

			@detection.currId += 1
			@detection.save

			if @detection.currId == @detection.value.values.length
				redirect_to results_detection_path(@detection)
			else
				redirect_to test_detection_path(@detection)
				#redirect_to test_detection_path(@detection, :anchor => "samples")
			end
		end

	end

	def results
		@detection = Detection.find(params[:id])


		#NB: NOW is ACCURACY
		f1den = @detection.tp + @detection.fn + @detection.fp + @detection.tn

		if f1den == 0
			@f1score = number_with_precision(0.0);
		else
			@f1score = number_with_precision( ( @detection.tp.to_f + @detection.tn.to_f ) / f1den.to_f * 100 )
		end

		sensden = @detection.tp + @detection.fn

		if sensden == 0
			@sensitivity = number_with_precision(0.0)
		else
			@sensitivity = number_with_precision( @detection.tp.to_f / sensden.to_f * 100 )
		end

		specden = @detection.tn + @detection.fp
		
		if specden == 0
			@specificity = number_with_precision(0.0)
		else
			@specificity = number_with_precision( @detection.tn.to_f / specden.to_f * 100 )
		end

	end

	def index
		detections = Detection.all

		@detectionsindex = Array.new

		detections.each do |d|

			case d.user
				when 1
					type = "newbie"
				when 2
					type = "biologist"
				when 3
					type = "histologist"
			end

			case d.sight
				when 1
					sight = "normal"
				when 2
					sight = "colorblind"
			end

			tot_time = 0

			d.value.values.each do |v|
				if !v[3].to_s["u"].nil?
					break
				else
					tot_time += v[4]
				end
			end

			tot_det = d.tp + d.tn + d.fp + d.fn

			if tot_time == 0
				avg = 0.0
			else
				avg = number_with_precision( tot_time.to_f / tot_det.to_f )
			end

					
			@detectionsindex << [d.code, type, sight, d.nickname, tot_det, d.tp, d.tn, d.fp, d.fn, avg, d.updated_at  ]
		end
	end

	def search
		# puts "PARAMS pippo #{params}"
		@detection = Detection.find_by_code(params[:code])

		if @detection.nil?
			flash[:error] = "No Detection found with code #{params[:code]}"
			redirect_to(root_path)
		else
			flash[:success] = "OK"
			redirect_to results_detection_path(@detection)
		end
	end

	def download

		detections = Detection.all

		csv = CSV.generate do |csv|
			detections.each do |d|
				csv << ["USER",d.user,d.sight,d.nickname,d.updated_at,d.tp,d.fn,d.tn,d.fp,d.code]
				d.value.values.each do |v|
					if !v[3].to_s["u"].nil?
						break
					else
						if v[1]['1'].nil?
							# neg image
							im = Evalnegative.find(v[0])
							tot_id = v[0] + Evalpositive.count
						elsif v[1]['0'].nil?
							#pos image
							im = Evalpositive.find(v[0])
							tot_id = v[0]
						else
							puts "unknown image"
							break;
						end

						csv << [tot_id,im.image.split('.')[0],im.x,im.y,v[1],v[3],v[4]]

					end
				end
			end
		end

		send_data csv, :type => 'text/csv', :filename => 'user.csv', :disposition => 'attachment'

		#redirect_to detections_path
	end

	def imagedownload

		csv = CSV.generate do |csv|

			ep = Evalpositive.all

			ep.each do |im|
				csv << [im.id,'1',im.image.split('.')[0],im.x,im.y,im.positives]
			end

			en = Evalnegative.all

			en.each do |im|

app/helpers/detections_helper.rb
module DetectionsHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
	def thumb_for(user)
		case user
			when 1 # new
				thumb_url = "/assets/newbie.gif"
				type = "newbie"
			when 2 # returning
				thumb_url = "/assets/ret.gif"
				type = "returning"
			when 3 # experienced
				thumb_url = "/assets/experienced.gif"
				type = "experienced"
			else
				thumb_url = "/assets/rails.png"
				type = "unknown"
		end
		image_tag(thumb_url, alt: type, title: type ,class: "media-object", width: "64px")
	end
end

app/views/detections/comment.html.erb
<% provide(:title, @detection.code) %>

<%= form_tag(commentsave_detection_path(@detection), :method=>'get', :multipart => true)  do %>
<div class="row-fluid">
	<div class="span6 offset3">
		<p class="text-info">(optional) briefly describe the classification criteria you devised:</p>
	</div>
</div>
<div class="row-fluid">
	<div class="span6 offset3 well">
		<%= text_area(:comment, :text, :cols => 40, :rows => 15) %>
	</div>
</div>
<div class="row-fluid">
	<div class="span6 offset3 divCenter">
		<p><%= submit_tag "View your results", class: "btn btn-primary" %></p>		
	</div>
</div>
<% end %>

app/views/detections/comments.html.erb
<% provide(:title, 'All Comments') %>

<div class="row-fluid">
	<div class="span12">
		<h1>All Comments</h1>
	</div>
</div>

<div class="row-fluid">
	<%if @comments.empty? %>
		<div class="span6 offset3">
			<p class="lead">No comments yet</p>
		</div>
	<% else %>
		<div class="span8 offset2">
			<table class="table">
				<% @comments.each do |c| %>
					<tr>
						<td>
							<blockquote>
								<p><%= c[3] %></p>
								<small><%= c[0] %>, <cite title="Pippo"><%= c[1] %>, <%= c[2] %></cite> - <%= c[4] %></small>
							</blockquote>
						</td>
					</tr>
				<% end %>
			</table>
		</div>
	<% end %>
</div>

app/views/detections/index.html.erb
<% provide(:title, 'All Detections') %>

<div class="row-fluid">
	<div class="span12">
		<h1>All Detections</h1>
	</div>
</div>

<% if @detectionsindex.nil? %>
<div class="row-fluid">
	<div class="span12 well">
		<p class="text-info">No detections found, at the moment</p>
	</div>
</div>

<% else %>
<div class="row-fluid">
	<table class="table table-hover">
		<caption>Detections completed:</caption>
		<thead>
			<tr>
				<th>Code</th>
				<th>User</th>
				<th>Ability</th>
				<th>Nickname</th>
				<th>Total</th>
				<th>TP</th>
				<th>TN</th>
				<th>FP</th>
				<th>FN</th>
				<th>Avg. time</th>
				<th>Date</th>
			</tr>
		</thead>
		<tbody>
			<% @detectionsindex.each do |d| %>
				<tr>
					<% (0..10).each do |k| %>
						<td><%= d[k] %></td>
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

<% end %>

<div class="row-fluid">
	<div class="span2 offset2 divCenter">
		<p><%= link_to "Download data", download_detections_path, class: "btn btn-primary" %></p>
	</div>
	<div class="span2 offset1 divCenter">
		<p><%= link_to "Download image data", imagedownload_detections_path, class: "btn btn-primary" %></p>
	</div>
	<div class="span2 offset1 divCenter">
		<p><%= link_to "View Comments", comments_detections_path, class: "btn btn-primary" %></p>
	</div>
</div>

app/views/detections/new.html.erb
<% provide(:title, 'Start') %>


<h1>Introduction</h1>

<!-- Intro -->
<div class="row-fluid">
	<div class="well span12">
		<div class="row-fluid">
			<div class="span10 offset1">
				<h2>Image classification experiment on the <abbr title="M I T O S">MITOS</abbr> dataset</h2>
				<p>
					Detecting and counting mitotic nuclei is an important part of the evaluation of breast cancer histological images. However, distinguishing mitotic nuclei from non-mitotic nuclei and other similar structures is hard and time-consuming, therefore researchers are designing automated algorithms for assisting histologists in this task.
				</p>
				<p>
					Algorithms learn to detect mitotic nuclei by looking at a large number of examples.  In this experiment, we want to compare their accuracy with the accuracy of humans who are new to the problem and are faced with the same task.
				</p>
				<p>The experiment is divided in two phases:</p>
				<dl class="dl-horizontal">
					<dt>
						TRAINING:
					</dt>
					<dd>we will show several labeled images including known mitotic nuclei, as well as other structures which look similar but are known NOT to be mitotic nuclei. Just like our algorithms, you should try to find out some criteria to tell the two classes apart.</dd>
					<dt>
						EVALUATION:
					</dt>
					<dd>then, we will show several unlabeled images, and you will be asked to classify each of them as either <span class="label label-info">MITOSIS</span> or <span class="label label-warning">NON-MITOSIS</span>. During evaluation, you still have access to the full set of training examples to use as a reference, and you can take as much time as you want.</dd>
				</dl>
				<p class="info">The experiment should take roughly <b>10 - 15 minutes</b>: you can classify as few or as many samples you want and exit at any time, and your results will be useful to us.
				</p>
			</div>
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="span5 offset3">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><strong><%= value %></strong></div>
		<% end %>
	</div>
</div>



<!-- FORM -->
<div class="row-fluid">
	<div class="span5 offset3">
		<p>Please tell us something about you:</p>
		<%= form_for(@detection) do |f| %>

		<%= render 'shared/error_messages' %>

		<%= f.select :user, [["I don't work in medicine/biology",1],
							 ["I work in medicine/biology but I am not an histologist",2],
							 ["I am an histologist",3]] ,
		{:prompt => 'Your experience?'} %>

		<%= f.select :sight, [["I have normal color vision",1],
							 ["I am colorblind",2]] ,
		{:prompt => 'Your color vision ability?'} %>


		<%= f.label :nickname %>
		<p class="text-info">(You can leave it blank)</p>
		<%= f.text_field :nickname %>


		<%= f.submit "Begin the Experiment", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="row-fluid">
	<div class="well span12">
		<div class="row-fluid">
			<div class="span10 offset1">
				<p>
					<small>
						The data used in this experiment is part of the public <a href="http://ipal.cnrs.fr/ICPR2012/?q=node/5">MITOS dataset</a>, built for project MITO by experienced pathologists at the Piti&eacute;-Salp&ecirc;tri&egrave;re Hospital in Paris, France.
					</small>
				</p>
			</div>
		</div>
	</div>
</div>

app/views/detections/results.html.erb
<% provide(:title, @detection.code) %>

<div class="row-fluid">
<% if flash[:success].nil? %>
	<h2><strong>Thank you very much for your collaboration!</strong></h2>
	<div class="span6 offset3">
		<div class="divCenter alert alert-info"><strong>Please DO NOT retry this test</strong></div>
	</div>
<% else %>
	<h2>Results for session <strong><%= @detection.code %></strong></h2>
<% end %>
</div>

<div class="row-fluid">
	<div class="span3">Session code: <strong><%= @detection.code%></strong></div>
	<div class="span8">Here are your results:</div>
</div>
<div class="row-fluid">
	<div class="span4 offset4">
		<table class="table table-hover">
			<caption><strong>Detection results</strong></caption>
			<tr class="success">
				<td>True positives: <%= @detection.tp%></td>
				<td>True negatives: <%= @detection.tn%></td>
			</tr>
			<tr class="error">
				<td>False positives: <%= @detection.fp%></td>
				<td>False negatives: <%= @detection.fn%></td>
			</tr>
		</table>
	</div>
</div>
<div class="row-fluid">
	<div class="span4 offset4">
		<table class="table table-hover">
			<tr>
				<td>Your <em>Accuracy</em> is:</td>
				<td><strong><%= @f1score %>%</strong></td>
			</tr>
			<tr>
				<td>Your <em>Sensitivity</em> is:</td>
				<td><strong><%= @sensitivity %>%</strong></td>
			</tr>
			<tr>
				<td>Your <em>Specificity</em> is:</td>
				<td><strong><%= @specificity %>%</strong></td>
			</tr>
			<tr>
				<td>
				</td>
			</tr>
			<tr>
				<td>Average Accuracy of <em>humans</em> is:</td>
				<td><strong>66%</strong></td>
			</tr>
			<tr>
				<td>Accuracy of <em>best humans</em> is:</td>
				<td><strong>80% to 85%</strong></td>
			</tr>
			<tr>
				<td>Accuracy of <em>best algorithms</em> is:</td>
				<td><strong>&#126;87%</strong></td>
			</tr>
		</table>
	</div>
</div>

app/views/detections/show.html.erb
<% provide(:title, @detection.code) %>


<h1>Training</h1>

<div class="row-fluid">
	<div class="well well-small span12">
		<div class="row-fluid">
			<div class="span10 offset1">
				<p>
					Carefully look at examples for both classes. When you are ready to continue, press the button below.
				</p>
				<p>
					Training examples will remain visible during the next phase as a reference.
				</p>
			</div>
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="span12">
		<a name="samples"></a>
		<p>&nbsp;</p>
	</div>	
</div>

<div class="row-fluid">
	<div class="span6 well pull-left">
		<div class="row-fluid">
			<div class="span12">
				<p class="text-info">Some examples: <span class="label label-info">Mitosis</span></p>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span12 withscroll">
				<% (0..53).each do |row_index| %>
					<div class="row-fluid">
						<ul class="thumbnails">
							<% (0..3).each do |col_index| %>
								<li class="span3">
									<a href="#samples" class="thumbnail">
										<% code = @positive_keys[row_index * 4 + col_index] %>
										<%= image_tag(@detection.positive_training[code][1], alt: code, title: code, class: "imgzoom") %>
									</a>
								</li>
							<% end %>
						</ul>
					</div>
				<% end %>
			</div>
			<p class="text-info"><span class="label label-info">scroll</span> to view more samples</p>
		</div>
	</div>
	<div class="span6 well pull-right">
		<div class="row-fluid">
			<div class="span12">
				<p class="text-info">Some examples: <span class="label label-warning">NON Mitosis</span></p>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span12 withscroll">
				<% (0..53).each do |row_index| %>
					<div class="row-fluid">
						<ul class="thumbnails">
							<% (0..3).each do |col_index| %>
								<li class="span3">
									<a href="#samples" class="thumbnail">
										<% code = @negative_keys[row_index * 4 + col_index] %>
										<%= image_tag(@detection.negative_training[code][1], alt: code, title: code, class: "imgzoom") %>
									</a>
								</li>
							<% end %>
						</ul>
					</div>
				<% end %>
			</div>
			<p class="text-info"><span class="label label-info">scroll</span> to view more samples</p>
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="span12 well divCenter">
		<%= link_to "CONTINUE TO NEXT PHASE", test_detection_path(@detection), class: "btn btn-primary" %></br>
		<p class="text-info">
			<small>(training examples will remain visible)</small>
		</p>
	</div>

</div>

app/views/detections/test.html.erb
<% provide(:title, @detection.code) %>

<h1>Classification</h1>


<!-- Intro -->
<div class="row-fluid">
	<div class="span12 well">
		<div class="row-fluid">
			<div class="span10 offset1">
				<p class="text-info">
					Please give your best guess for the example below. Roughly 50% of the samples we show are
					<span class="label label-info">Mitosis</span> and 50% are <span class="label label-warning">NON Mitosis</span>.
				</p>
			</div>
		</div>
	</div>
</div>


<!-- message -->
<div class="row-fluid">
	<div class="span12">
		<% flash.each do |key, value| %>
			<div class="divCenter alert alert-<%= key %>"><strong><%= value %></strong></div>
		<% end %>
	</div>
</div>
<!-- -->

	
<div class="row-fluid">
	<div class="span4">
		<h4>Your current performance:</h4>
		<% if @detection.currId < 20 %>
			<p class="text-info">your performance will be available after 20 detections</p>
		<% else %>
			<p class="text-info">
				<ul class="unstyled">
					<li>Your current <em>Accuracy</em> is: <strong><%= @f1score %>%</strong></li>
					<li>Average accuracy of <em>humans</em> is: <strong>66%</strong></li>
					<li>Accuracy of <em>best humans</em> is: <strong>80% to 85%</strong></li>
					<li>Accuracy of <em>best algorithms</em> is: <strong>&#126;87%</strong></li>
				</ul>
			</p>
		<% end %>
	</div>

	<div div class="span8 well">
				<%= form_tag(save_detection_path(@detection.id), :method=>'get', :multipart => true)  do %>
		<div class="row-fluid">
			<div class="span3">
				<p class="text-info">Sample <em><%= @detection.currId+1 %></em></p>
				<div class="thumbnail">
					<a href="#samples" class="thumbnail">
						<%= image_tag(@detection.value[@curr_image_code][2], alt: @curr_image_code, title: @curr_image_code, class: "imgzoom") %>
					</a>
				</div>
			</div>
			<div class="span4">
				<p class="text-info">Your guess:</p>
				<p>
					<%= submit_tag "Definitely Mitosis", class: "btn btn-info btn-block", name: "mit_pp" %>
				</p>
				<p>
					<%= submit_tag "Probably Mitosis", class: "btn btn-info btn-block", name: "mit_qp" %>
				</p>
				<p>
					<%= submit_tag "Probably NON Mitosis", class: "btn btn-warning btn-block", name: "mit_qn" %>
				</p>
				<p>
					<%= submit_tag "Definitely NON Mitosis", class: "btn btn-warning btn-block", name: "mit_nn" %>
				</p>
					<% end %>
			</div>
			<div class="span5">
				<div class="row-fluid">
					<div class="span8 offset2 divCenter">
						<p>&nbsp;</p>
						<p class="text-info">Whenever you want, you can</p>
						<p><%= link_to "Finish your test", comment_detection_path(@detection), class: "btn btn-primary" %></p>
						<p class="text-info">and see how you did.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>



<!-- TRAINING SAMPLES -->
<div class="row-fluid">
	<div class="span12">
		<a name="samples"></a>
		<p>&nbsp;</p>
	</div>	
</div>

<div class="row-fluid">
	<div class="span6 well pull-left">
		<div class="row-fluid">
			<div class="span12">
				<p class="text-info">Training Set: <span class="label label-info">Mitosis</span></p>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span12 withscroll">
				<% (0..53).each do |row_index| %>
					<div class="row-fluid">
						<ul class="thumbnails">
							<% (0..3).each do |col_index| %>
								<li class="span3">
									<a href="#samples" class="thumbnail">
										<% code = @positive_keys[row_index * 4 + col_index] %>
										<%= image_tag(@detection.positive_training[code][1], alt: code, title: code, class: "imgzoom") %>
									</a>
								</li>
							<% end %>
						</ul>
					</div>
				<% end %>
			</div>
			<p class="text-info"><span class="label label-info">scroll</span> to view more samples</p>
		</div>
	</div>
	<div class="span6 well pull-right">
		<div class="row-fluid">
			<div class="span12">
				<p class="text-info">Training Set: <span class="label label-warning">NON Mitosis</span></p>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span12 withscroll">
				<% (0..53).each do |row_index| %>
					<div class="row-fluid">
						<ul class="thumbnails">
							<% (0..3).each do |col_index| %>
								<li class="span3">
									<a href="#samples" class="thumbnail">
										<% code = @negative_keys[row_index * 4 + col_index] %>
										<%= image_tag(@detection.negative_training[code][1], alt: code, title: code, class: "imgzoom") %>
									</a>
								</li>
							<% end %>
						</ul>
					</div>
				<% end %>
			</div>
			<p class="text-info"><span class="label label-info">scroll</span> to view more samples</p>
		</div>
	</div>
</div>