config/routes.rb
Tydes::Application.routes.draw do
  resources :detections do
    member do
      get :test, :save, :results, :comment, :commentsave
    end

    collection do
      get :search, :as => :search
      get :download, :as => :download
      get :imagedownload, :as => :imagedownload
      get :comments, :as => :comments
    end
  end

  root to: 'detections#new'

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/news',  to: 'static_pages#updates'

end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom navbar-inverse">
	<div class="navbar-inner">
		<div class="container-fluid">
			<ul class="nav pull-left">
				<li>
					<%= link_to "TYDES Project", '#', class: "brand" %>
				</li>
				<li class="header">author: CC</li>
			</ul>
			<ul class="nav pull-right">
				<li class="divider-vertical"></li>
				<li><%= link_to " ",    detections_path %></li>
			</ul>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container-fluid">
			<%= link_to "Mitosis Detection Experiment", '#', id: "logo", class: "brand" %>
			<nav>
				<ul class="nav pull-right">
					<li class="header">View results:</li>
					<li>
						<form class="navbar-search" action="/detections/search" method="get">
							<input type="text" name="code" class="search-query" placeholder="insert code..." maxlength="5"/>
						</form>
					</li>
					<li class="divider-vertical"></li>
					<li><%= link_to "Home",    root_path %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_navbar.html.erb
<ul class="nav nav-list well"  data-spy="affix" data-offset-top="10" id="navbar">
	<li class="nav-header">Sections</li>
	<li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
	<li class="divider"></li>
	<li class="<%= 'active' if current_page?(start_path) %>"><%= link_to "Start", start_path %></li>
	<li class="divider"></li>
	<li class="nav-header">Contents</li>
	<li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
	<li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Contact", contact_path %></li>
	<li class="<%= 'active' if current_page?(help_path) %>"><%= link_to "Help", help_path %></li>
	<li class="<%= 'active' if current_page?(news_path) %>"><%= link_to "News", news_path %></li>
</ul>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    "application", media: "all" %>
		<%= javascript_include_tag(:application) %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>

	<body>
		<%= render 'layouts/header' %>
		<div class="container-fluid">
			<div class="row-fluid">
				<div class="span2">
					&nbsp;
				</div>
				<div class="span10">
					&nbsp;
				</div>
			</div>
			<div class="row-fluid">
				<div class="span12">
					<%= yield %>
				</div>
			</div>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>